erDiagram
    %% Tabele podstawowe
    SPORTS ||--o{ LEAGUES : "SPORT_ID"
    SPORTS ||--o{ PLAYERS : "SPORTS_ID"
    SPORTS ||--o{ TEAMS : "SPORTS_ID"

    COUNTRIES ||--o{ LEAGUES : "COUNTRY"
    COUNTRIES ||--o{ PLAYERS : "CURRENT_COUNTRY"
    COUNTRIES ||--o{ TEAMS : "COUNTRY"

    SEASONS ||--o{ LEAGUES : "CURRENT_SEASON_ID"
    SEASONS ||--o{ MATCHES : "SEASON"
    SEASONS ||--o{ TRANSFERS : "SEASON_ID"

    %% Tabele związane z meczami
    LEAGUES ||--o{ MATCHES : "LEAGUE"

    TEAMS ||--o{ MATCHES : "HOME_TEAM"
    TEAMS ||--o{ MATCHES : "AWAY_TEAM"
    TEAMS ||--o{ PLAYERS : "CURRENT_CLUB"
    TEAMS ||--o{ HOCKEY_MATCH_EVENTS : "TEAM_ID"
    TEAMS ||--o{ HOCKEY_MATCH_PLAYER_STATS : "TEAM_ID"
    TEAMS ||--o{ HOCKEY_MATCH_ROSTERS : "TEAM_ID"
    TEAMS ||--o{ HOCKEY_ROSTERS : "TEAM_ID"
    TEAMS ||--o{ TRANSFERS : "OLD_TEAM_ID"
    TEAMS ||--o{ TRANSFERS : "NEW_TEAM_ID"

    MATCHES ||--o{ BETS : "MATCH_ID"
    MATCHES ||--o{ FINAL_PREDICTIONS : "MATCH_ID"
    MATCHES ||--o{ FOOTBALL_SPECIAL_ROUND_ADD : "MATCH_ID"
    MATCHES ||--o{ HOCKEY_MATCH_EVENTS : "MATCH_ID"
    MATCHES ||--o{ HOCKEY_MATCH_PLAYER_STATS : "MATCH_ID"
    MATCHES ||--o{ HOCKEY_MATCH_ROSTERS : "MATCH_ID"
    MATCHES ||--o{ HOCKEY_MATCHES_ADD : "MATCH_ID"
    MATCHES ||--o{ ODDS : "MATCH_ID"
    MATCHES ||--o{ PREDICTIONS : "MATCH_ID"

    %% Tabele związane z zakładami
    EVENTS ||--o{ BETS : "EVENT_ID"
    EVENTS ||--o{ FINAL_PREDICTIONS : "EVENT_ID"
    EVENTS ||--o{ HOCKEY_MATCH_EVENTS : "EVENT_ID"
    EVENTS ||--o{ ODDS : "EVENT_ID"
    EVENTS ||--o{ PREDICTIONS : "EVENT_ID"

    BOOKMAKERS ||--o{ BETS : "BOOKMAKER"
    BOOKMAKERS ||--o{ ODDS : "BOOKMAKER"

    %% Tabele związane z graczami
    PLAYERS ||--o{ HOCKEY_MATCH_EVENTS : "PLAYER_ID"
    PLAYERS ||--o{ HOCKEY_MATCH_PLAYER_STATS : "PLAYER_ID"
    PLAYERS ||--o{ HOCKEY_MATCH_ROSTERS : "PLAYER_ID"
    PLAYERS ||--o{ HOCKEY_ROSTERS : "PLAYER_ID"
    PLAYERS ||--o{ TRANSFERS : "PLAYER_ID"

    %% Tabele związane z kuponami
    GAMBLERS ||--o{ GAMBLER_PARLAYS : "GAMBLER_ID"
    GAMBLER_PARLAYS ||--o{ EVENTS_PARLAY : "PARLAY_ID"
    BETS ||--o{ EVENTS_PARLAY : "BET_ID"
